'use strict'
import {test, expect, chromium} from '@playwright/test';  
import * as landingPageLocator from './locator/landingPage.js';
import * as dataLocator from './test-data/data.js';
import * as settingLocator from './locator/settingLocator.js';
import * as applicationAnsweringLocator from './locator/applicationAnswering.js';
import * as profileLocator from './locator/profile.js';
import { testcase } from './ulti-function/reusableTestCase.js';

import { autoGenerationSignup } from './ulti-function/autoGenerationSignup.js';
import { sign } from 'crypto';

test('applying job', async ()=>{
    //create browser
    const browser = await chromium.launch(); 
    const context = await browser.newContext();
    const vizzy = await context.newPage();
    const mailinator = await context.newPage();
    

    //declare variable for locator
    const landingPageHeader = await landingPageLocator.headerLocators(vizzy);
    const setting = await settingLocator.createJobForm(vizzy);
    const application= await applicationAnsweringLocator.applicationAnswering(vizzy);
    const signUpField = await landingPageLocator.signUpFieldsLocators(vizzy);
    const mailinatorField = await landingPageLocator.mailinatorLocators(mailinator);
    
    
    //autoGenerated Email and password
    const email = autoGenerationSignup.emailAutoGenerate();
    const password = autoGenerationSignup.passwordAutoGenerate();
    const lastName = autoGenerationSignup.generateLastName();

    //paste in application URL
    await vizzy.goto(dataLocator.url.jobSpecificURL);
    await landingPageHeader.cookieAllow.click(); 

    //arrive on the landing page
    await expect(application.landingPage.getStartedButton).toBeVisible();
    await application.landingPage.getStartedButton.click();

    //Sign up
    await testcase.signUp(signUpField, autoGenerationSignup, mailinator, mailinatorField, email, password, lastName);

    //move on to answering questions
    await expect(vizzy).toHaveTitle(dataLocator.pageTitle.myApplication);
    await application.applyButton.click();
    


});